---
name: Enable automerge option if available
on:
  pull_request:
    branches:
      - main
jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.PAT }}